services:
  caddy:
    container_name: caddy-reverse-proxy
    image: ghcr.io/tuyenhn/my-caddy:v2.10.2
    restart: unless-stopped
    volumes:
      - ./conf:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
    network_mode: "host"

volumes:
  caddy_data:
  caddy_config:
